name: Daily Car Poster Generator

on:
  schedule:
    - cron: "0 7 * * *"   # هر روز ساعت ۷ صبح
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
      run: npm install -g pnpm && pnpm install

      - name: Run script
        run: node index.js
